In [1]:
# ----- SETUP (RUN ONCE) ------ Run second cell first
# Before running make sure you set your fork
# You can find this from your forked repo under the code button
# Only run once, or if you CANNOT cd (change directory)
# into the repository
# For this to work (in colab)
# you must have created a GITHUB token
# and added it to colab.

from google.colab import userdata
email = userdata.get('GITHUB_EMAIL')
username = userdata.get('GITHUB_USERNAME')

# Change this to your forked url!!
gh_repo_url = "https://github.com/guth-metzlerr/fungal-temp-analysis.git"

# NOTE: set your email as your email
!git config --global user.email {email}

# NOTE: Change your username
!git config --global user.name {username}

# NOTE: change the address to the address of your fork!
!git clone {gh_repo_url}

!pip install ncbi-genome-download
!pip install pybarrnap

Cloning into 'fungal-temp-analysis'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 50 (delta 25), reused 6 (delta 6), pack-reused 21 (from 1)
Receiving objects: 100% (50/50), 1.19 MiB | 3.48 MiB/s, done.
Resolving deltas: 100% (25/25), done.
Collecting ncbi-genome-download
  Downloading ncbi_genome_download-0.3.3-py2.py3-none-any.whl.metadata (10 kB)
Collecting appdirs (from ncbi-genome-download)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2026.2.25)
Downloading ncbi_genome_download-0.3.3-py2.py3-none-any.whl (26 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: appdirs, ncbi-genome-download
Successfully installed appdirs-1.4.4 ncbi-genome-download-0.3.3
Collecting pybarrnap
  Downloading pybarrnap-0.5.1-py3-none-any.whl.metadata (6.8 kB)
Collecting biopython>=1.80 (from pybarrnap)
  Downloading biopython-1.86-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting pyhmmer>=0.11.0 (from pybarrnap)
  Downloading pyhmmer-0.12.0-cp312-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython>=1.80->pybarrnap) (2.0.2)
Requirement already satisfied: psutil<8.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from pyhmmer>=0.11.0->pybarrnap) (5.9.5)
Downloading pybarrnap-0.5.1-py3-none-any.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 12.4 MB/s eta 0:00:00
Downloading biopython-1.86-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 91.1 MB/s eta 0:00:00
Downloading pyhmmer-0.12.0-cp312-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 76.2 MB/s eta 0:00:00
Installing collected packages: pyhmmer, biopython, pybarrnap
Successfully installed biopython-1.86 pybarrnap-0.5.1 pyhmmer-0.12.0

In [3]:
# ---- Change Directory to repository -----
# Run when first open jupyter notebook.
# If this fails, use above cell.
%cd fungal-temp-analysis

[Errno 2] No such file or directory: 'fungal-temp-analysis'
/content/fungal-temp-analysis

In [5]:
# make sure to run this cell to have access to this function below
def commit_and_push(repo_url, message):
    import os
    import subprocess
    from google.colab import userdata

    try:
        # change your username from mine to yours.
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        !git add .
        !git commit -m "{message}"
        !git push "https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git"
        print("Changes Saved to GitHub!")
    except Exception as e:
        print(e)

# Only call this function if you want to
def catch_up_to_main_repo():
    import os
    from google.colab import userdata
    try:
        username = "GITHUB_EMAIL"
        token = userdata.get("GITHUB_TOKEN")
        main_repo = "https://github.com/nkmwicz/fungal-temp-analysis.git"
        !git remote add upstream {main_repo}
        !git fetch upstream
        !git merge upstream/main
        !git push https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git
    except Exception as e:
        print(e)

In [8]:
# SOME NOTES
# %ls shows the available files in the repo to get names of files
# to read a tsv, use pd.read_csv but pass in sep="\t"
# to reperesent tabs as separators
%ls

fungal-temp-analysis/                       genbank/
GCA_009665985.1_ASM966598v1_genomic.fna.gz  sample_data/

In [ ]:
# columns needed
# remove rows that aren't fungi ()
# remove those without temp.
# name, assembly, temp

In [ ]:
#import pandas as pd
#df = pd.read_csv("./delete_me.csv")
#df.loc[len(df)] = [11,12,13,14]
#df.to_csv("./delete_me.csv", index=False)

In [6]:
import pandas as pd

df = pd.read_csv("eukaryotes_ncbi_temperatures.csv")
df.head()

,#Organism Name,Organism Groups,Strain,BioSample,BioProject,Assembly,Level,Size(Mb),GC%,Replicons,WGS,Scaffolds,CDS,Release Date,GenBank FTP,RefSeq FTP,Temperature (°C)
0,Neopyropia yezoensis,Eukaryota;Other;Other,NaN,SAMN13316713,PRJNA589917,GCA_009829735.1,Chromosome,107.591,64.8454,chromosome 1:CM020618.1; chromosome 2:CM020619...,WMLA01,28,0,2020-01-03T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009...,NaN,NaN
1,Emiliania huxleyi CCMP1516,Eukaryota;Protists;Other Protists,CCMP1516,SAMN02744062,PRJNA77753,GCA_000372725.1,Scaffold,167.676,64.5000,NaN,AHAL01,7795,38554,2013-04-19T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN
2,Glycine max,Eukaryota;Plants;Land Plants,NaN,SAMN00002965,PRJNA19861,GCA_000004515.5,Chromosome,978.942,35.1221,chromosome 1:NC_016088.4/CM000834.4; chromosom...,ACUP04,347,74248,2010-01-05T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN
3,Medicago truncatula,Eukaryota;Plants;Land Plants,NaN,SAMN08400029,PRJNA702529,GCA_003473485.2,Chromosome,430.008,33.4462,chromosome 1:NC_053042.1/CM010648.1; chromosom...,PSQE01,42,42683,2018-09-06T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003...,NaN
4,Solanum lycopersicum,Eukaryota;Plants;Land Plants,NaN,SAMN02981290,PRJNA119,GCA_000188115.3,Chromosome,828.349,35.6991,chromosome 1:NC_015438.3/CM001064.3; chromosom...,AEKE03,3150,37660,2010-12-10T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN

In [7]:
columns = ["#Organism Name", "Organism Groups", "Assembly", "Temperature (°C)"]
df = df[columns]
df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
0,Neopyropia yezoensis,Eukaryota;Other;Other,GCA_009829735.1,NaN
1,Emiliania huxleyi CCMP1516,Eukaryota;Protists;Other Protists,GCA_000372725.1,NaN
2,Glycine max,Eukaryota;Plants;Land Plants,GCA_000004515.5,NaN
3,Medicago truncatula,Eukaryota;Plants;Land Plants,GCA_003473485.2,NaN
4,Solanum lycopersicum,Eukaryota;Plants;Land Plants,GCA_000188115.3,NaN

In [8]:
df = df.dropna(subset="Temperature (°C)")
df.shape

(972, 4)

In [9]:
df = df.loc[df['Organism Groups'].str.contains("Fung")]
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0
...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0

In [10]:
df.drop_duplicates(subset="Assembly")
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0
...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0

In [11]:
import re #re stands for regex
df['species_root_name'] = df['#Organism Name'].apply(lambda item: " ".join(item.split(" ")[:2]))
df['species_root_name'] = df['species_root_name'].apply(lambda item: re.sub(r"[\]\[\;'\",\(\)\-\:\.]", "", item)) #removes extra non-alphabetic characters, using the \ indicates the next thing is like a string and not a coding character
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans
...,...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0,Hanseniaspora lindneri
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0,Cystobasidium slooffiae
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0,Candida anglica
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0,Penicillium brevicompactum
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0,Agaricus bisporus

In [12]:
len(df['species_root_name'].unique()) #len gets the length of the list and unique is inside of that. So can check if this list is shorter than the original list

946

In [13]:
df = df.loc[~df['#Organism Name'].str.contains(" cf. ")] #removes any entries that have cf. in their name
df.shape

(954, 5)

In [14]:
df['duplicate'] = df.duplicated(subset="species_root_name", keep=False) #creates a new column called duplicate
df.head()

/tmp/ipykernel_8791/2971040398.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['duplicate'] = df.duplicated(subset="species_root_name", keep=False) #creates a new column called duplicate

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False

In [15]:
df = df.loc[~df['#Organism Name'].str.contains(" cf. ")]
df.shape

(954, 6)

In [16]:
df = df.reset_index(drop=True)
df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
0,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
1,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
2,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
3,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
4,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False

In [17]:
!ncbi-genome-download -h

usage: ncbi-genome-download [-h] [-s {refseq,genbank}] [-F FILE_FORMATS]
                            [-l ASSEMBLY_LEVELS] [-g GENERA] [--genus GENERA]
                            [--fuzzy-genus] [-S STRAINS] [-T SPECIES_TAXIDS]
                            [-t TAXIDS] [-A ASSEMBLY_ACCESSIONS]
                            [--fuzzy-accessions] [-R REFSEQ_CATEGORIES]
                            [--refseq-category REFSEQ_CATEGORIES] [-o OUTPUT]
                            [--flat-output] [-H] [-P] [-u URI] [-p N] [-r N]
                            [-m METADATA_TABLE] [-n] [-N] [-v] [-d] [-V]
                            [-M TYPE_MATERIALS]
                            groups

positional arguments:
  groups                The NCBI taxonomic groups to download (default: all).
                        A comma-separated list of taxonomic groups is also
                        possible. For example: "bacteria,viral"Choose from:
                        ['all', 'archaea', 'bacteria', 'fungi',
                        'invertebrate', 'metagenomes', 'plant', 'protozoa',
                        'vertebrate_mammalian', 'vertebrate_other', 'viral']

options:
  -h, --help            show this help message and exit
  -s {refseq,genbank}, --section {refseq,genbank}
                        NCBI section to download (default: refseq)
  -F FILE_FORMATS, --formats FILE_FORMATS
                        Which formats to download (default: genbank).A comma-
                        separated list of formats is also possible. For
                        example: "fasta,assembly-report". Choose from:
                        ['genbank', 'fasta', 'rm', 'features', 'gff',
                        'protein-fasta', 'genpept', 'wgs', 'cds-fasta', 'rna-
                        fna', 'rna-fasta', 'assembly-report', 'assembly-
                        stats', 'translated-cds', 'all']
  -l ASSEMBLY_LEVELS, --assembly-levels ASSEMBLY_LEVELS
                        Assembly levels of genomes to download (default: all).
                        A comma-separated list of assembly levels is also
                        possible. For example: "complete,chromosome". Choose
                        from: ['all', 'complete', 'chromosome', 'scaffold',
                        'contig']
  -g GENERA, --genera GENERA
                        Only download sequences of the provided genera. A
                        comma-seperated list of genera is also possible. For
                        example: "Streptomyces coelicolor,Escherichia coli".
                        (default: [])
  --genus GENERA        Deprecated alias of --genera
  --fuzzy-genus         Use a fuzzy search on the organism name instead of an
                        exact match.
  -S STRAINS, --strains STRAINS
                        Only download sequences of the given strain(s). A
                        comma-separated list of strain names is possible, as
                        well as a path to a filename containing one name per
                        line.
  -T SPECIES_TAXIDS, --species-taxids SPECIES_TAXIDS
                        Only download sequences of the provided species NCBI
                        taxonomy IDs. A comma-separated list of species taxids
                        is also possible. For example: "52342,12325".
                        (default: [])
  -t TAXIDS, --taxids TAXIDS
                        Only download sequences of the provided NCBI taxonomy
                        IDs. A comma-separated list of taxids is also
                        possible. For example: "9606,9685". (default: [])
  -A ASSEMBLY_ACCESSIONS, --assembly-accessions ASSEMBLY_ACCESSIONS
                        Only download sequences matching the provided NCBI
                        assembly accession(s). A comma-separated list of
                        accessions is possible, as well as a path to a
                        filename containing one accession per line.
  --fuzzy-accessions    Use a fuzzy search on the entry accession instead of
                        an exact match.
  -R REFSEQ_CATEGORIES, --refseq-categories REFSEQ_CATEGORIES
                        Only download sequences of the provided refseq
                        categories [refrerence, representative, na]. A comma-
                        separated list of categories is also possible.
                        (default: download all categories)
  --refseq-category REFSEQ_CATEGORIES
                        Deprecated alias for --refseq-categories
  -o OUTPUT, --output-folder OUTPUT
                        Create output hierarchy in specified folder (default:
                        /content/fungal-temp-analysis)
  --flat-output         Dump all files right into the output folder without
                        creating any subfolders.
  -H, --human-readable  Create links in human-readable hierarchy (might fail
                        on Windows)
  -P, --progress-bar    Create a progress bar for indicating the download
                        progress
  -u URI, --uri URI     NCBI base URI to use (default:
                        https://ftp.ncbi.nih.gov/genomes)
  -p N, --parallel N    Run N downloads in parallel (default: 1)
  -r N, --retries N     Retry download N times when connection to NCBI fails
                        (default: 0)
  -m METADATA_TABLE, --metadata-table METADATA_TABLE
                        Save tab-delimited file with genome metadata
  -n, --dry-run         Only check which files to download, don't download
                        genome files.
  -N, --no-cache        Don't cache the assembly summary file in
                        /root/.cache/ncbi-genome-download.
  -v, --verbose         increase output verbosity
  -d, --debug           print debugging information
  -V, --version         print version information
  -M TYPE_MATERIALS, --type-materials TYPE_MATERIALS
                        Specifies the relation to type material for the
                        assembly (default: any). "any" will include assemblies
                        with no relation to type material value defined, "all"
                        will download only assemblies with a defined value. A
                        comma-separated list of relatons. For example:
                        "reference,synonym". Choose from: ['any', 'all',
                        'type', 'reference', 'synonym', 'proxytype',
                        'neotype'] .

In [5]:
!ncbi-genome-download --section genbank --assembly-accessions GCA_009665985.1 --formats fasta fungi

In [7]:
!tar -xzvf GCA_009665985.1_genomic.fna.gz

tar (child): GCA_009665985.1_genomic.fna.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

In [ ]:
#for row in range(1):
#assembly = "GCA_009665985.1"
#!ncbi-genome-download --section genbank --assembly-accessions {assembly} --formats fasta fungi

In [ ]:
import subprocess, requests, zipfile, os #Changed tarfile to zipfile to open a zipfile
from zipfile import ZipFile
from pybarrnap import Barrnap
from pybarrnap.utils import load_example_fasta_file
# get fasta files
# unzip fasta
# barrnap fasta file for quality.
# get tRNA & save it in df
# scrape web for it????
for row in range(1):
    assembly = df.at[row, 'Assembly']
    url = f"https://api.ncbi.nlm.nih.gov/datasets/v2/genome/accession/{assembly}/download?include_annotation_type=GENOME_FASTA"
    res = requests.get(url)  # this returns a zip folder

    # Define the filename for the downloaded zip file
    zip_filename = f"{assembly}.zip"
    # Save the zip file
    # Use 'wb' mode to write binary data to the zip file
    with open(zip_filename, 'wb') as f: #Changed from tarfile to open to write the file
        for chunk in res.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"Downloaded: {zip_filename}")
    extract_dir = f"{assembly}_dir"
    os.mkdir(extract_dir)

    with ZipFile(zip_filename, 'r') as zip_ref: #Changed from tarfile to zipfile to open and extract the zipfile
        zip_ref.extractall(extract_dir) #Changed from tar.extractall to zip_ref.extractall to work with a zipfile
    %cd {extract_dir}/ncbi_dataset/data/{assembly}
    fasta_file = os.listdir()[0] #fasta is a list of the name of files it finds
    print(fasta_file)
    #do stuff here with the fasta
    #Pybarnapp
    # Run pybarrnap rRNA prediction
    barrnap = Barrnap(
        fasta_file,
        evalue=1e-6,
        lencutoff=0.8,
        reject=0.25,
        threads=1,
        kingdom="euk",
        accurate=False,
        quiet=False,
    )
    result = barrnap.run()
    # Get rRNA GFF text and print
    print("\n========== Print rRNA GFF ==========")
    print(result.get_gff_text())

    # Get rRNA features and print
    print("\n========== Print rRNA features ==========")
    for rec in result.seq_records:
        for feature in rec.features:
            print(feature.id, feature.type, feature.location, feature.qualifiers)

    %cd ../../../../
    %rm -rf {extract_dir}
    # !ncbi-genome-download --section genbank --assembly-accessions {assembly} --formats fasta fungi

Downloaded: GCA_000002945.2.zip
/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2
GCA_000002945.2_ASM294v2_genomic.fna

========== Print rRNA GFF ==========
##gff-version 3
CU329670.1	pybarrnap:0.5.1	rRNA	149660	149774	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	456529	456643	4.7e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	912232	912346	1.9e-21	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	1563477	1563591	2.1e-21	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	2976821	2976935	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3165398	3165512	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3547902	3548016	7.9e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3634373	3634487	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3830382	3830496	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3891665	3891779	7.9e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	4184357	4184471	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	4240852	4240966	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	464529	464643	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	520305	520419	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	569153	569267	1.0e-20	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	783261	783375	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	1199929	1200043	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	1406587	1406701	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	1504375	1504489	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2032412	2032526	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2261373	2261487	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2322735	2322849	2.8e-21	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2442703	2442817	1.0e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	3096971	3097072	1.2e-07	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	3171574	3171678	3.1e-12	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	3938580	3938694	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	4161625	4161735	1.0e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	4210383	4210497	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	16	1389	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA (partial);Dbxref=RFAM:RF01960;Note=aligned only 73.52 percent of the 18S ribosomal RNA
CU329672.1	pybarrnap:0.5.1	rRNA	6045	9537	0	-	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.1	rRNA	9845	9997	6.7e-45	-	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.1	rRNA	10420	12259	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.1	rRNA	16915	20407	0	-	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.1	rRNA	20715	20867	6.7e-45	-	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.1	rRNA	21290	23129	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.1	rRNA	523319	523433	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	853316	853430	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	926144	926258	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1370036	1370150	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1474261	1474375	4.4e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1690947	1691061	4.4e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1702126	1702240	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	2308168	2308282	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	2440995	2442834	0	+	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.1	rRNA	2443257	2443409	6.7e-45	+	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.1	rRNA	2443717	2447209	0	+	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.1	rRNA	2451884	2452883	1.3e-272	+	.	Name=18S_rRNA;product=18S ribosomal RNA (partial);Dbxref=RFAM:RF01960;Note=aligned only 53.50 percent of the 18S ribosomal RNA


========== Print rRNA features ==========
CU329670.1 rRNA [149659:149774](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [456528:456643](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [912231:912346](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [1563476:1563591](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [2976820:2976935](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3165397:3165512](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3547901:3548016](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3634372:3634487](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3830381:3830496](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3891664:3891779](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [4184356:4184471](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [4240851:4240966](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [464528:464643](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [520304:520419](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [569152:569267](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [783260:783375](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [1199928:1200043](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [1406586:1406701](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [1504374:1504489](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2032411:2032526](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2261372:2261487](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2322734:2322849](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2442702:2442817](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [3096970:3097072](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [3171573:3171678](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [3938579:3938694](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [4161624:4161735](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [4210382:4210497](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [15:1389](-) {'gene': ['18S_rRNA'], 'product': ['18S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF01960'], 'note': ['aligned only 73.52 percent of the 18S ribosomal RNA']}
CU329672.1 rRNA [6044:9537](-) {'gene': ['28S_rRNA'], 'product': ['28S ribosomal RNA'], 'db_xref': ['RFAM:RF02543']}
CU329672.1 rRNA [9844:9997](-) {'gene': ['5_8S_rRNA'], 'product': ['5.8S ribosomal RNA'], 'db_xref': ['RFAM:RF00002']}
CU329672.1 rRNA [10419:12259](-) {'gene': ['18S_rRNA'], 'product': ['18S ribosomal RNA'], 'db_xref': ['RFAM:RF01960']}
CU329672.1 rRNA [16914:20407](-) {'gene': ['28S_rRNA'], 'product': ['28S ribosomal RNA'], 'db_xref': ['RFAM:RF02543']}
CU329672.1 rRNA [20714:20867](-) {'gene': ['5_8S_rRNA'], 'product': ['5.8S ribosomal RNA'], 'db_xref': ['RFAM:RF00002']}
CU329672.1 rRNA [21289:23129](-) {'gene': ['18S_rRNA'], 'product': ['18S ribosomal RNA'], 'db_xref': ['RFAM:RF01960']}
CU329672.1 rRNA [523318:523433](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [853315:853430](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [926143:926258](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1370035:1370150](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1474260:1474375](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1690946:1691061](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1702125:1702240](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [2308167:2308282](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [2440994:2442834](+) {'gene': ['18S_rRNA'], 'product': ['18S ribosomal RNA'], 'db_xref': ['RFAM:RF01960']}
CU329672.1 rRNA [2443256:2443409](+) {'gene': ['5_8S_rRNA'], 'product': ['5.8S ribosomal RNA'], 'db_xref': ['RFAM:RF00002']}
CU329672.1 rRNA [2443716:2447209](+) {'gene': ['28S_rRNA'], 'product': ['28S ribosomal RNA'], 'db_xref': ['RFAM:RF02543']}
CU329672.1 rRNA [2451883:2452883](+) {'gene': ['18S_rRNA'], 'product': ['18S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF01960'], 'note': ['aligned only 53.50 percent of the 18S ribosomal RNA']}
/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2

In [ ]:
%rm -rf {extract_dir}

In [ ]:
%

'/'

In [ ]:
%cd ncbi_dataset/data/{assembly}
%ls

In [ ]:
duplicated_species = df.loc[df['duplicate'] == True]
duplicated_species

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
47,Cryptococcus neoformans var. neoformans JEC21,Eukaryota;Fungi;Basidiomycetes,GCA_000091045.1,27.0,Cryptococcus neoformans,True
1069,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_009665985.1,25.0,Saccharomyces cerevisiae,True
1495,Ogataea polymorpha,Eukaryota;Fungi;Ascomycetes,GCA_001664045.1,25.0,Ogataea polymorpha,True
1541,Saccharomyces cerevisiae x Saccharomyces uvarum,Eukaryota;Fungi;Ascomycetes,GCA_013180185.1,25.0,Saccharomyces cerevisiae,True
2300,Magnusiomyces capitatus NRRL Y-17686,Eukaryota;Fungi;Ascomycetes,GCA_900497725.1,25.0,Magnusiomyces capitatus,True
4451,Magnusiomyces capitatus CNRMA 12.647,Eukaryota;Fungi;Ascomycetes,GCA_000817185.1,25.0,Magnusiomyces capitatus,True
4962,Cryptococcus neoformans AD hybrid,Eukaryota;Fungi;Basidiomycetes,GCA_006992865.1,27.0,Cryptococcus neoformans,True
5187,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009665555.1,25.0,Saccharomyces cerevisiae,True
5188,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009666275.1,25.0,Saccharomyces cerevisiae,True
5189,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009667055.1,25.0,Saccharomyces cerevisiae,True
5190,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_009666465.1,25.0,Saccharomyces cerevisiae,True
5661,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_013180725.1,25.0,Saccharomyces cerevisiae,True
7812,Ogataea polymorpha x Ogataea parapolymorpha,Eukaryota;Fungi;Ascomycetes,GCA_019381815.1,25.0,Ogataea polymorpha,True

In [19]:
#Install condacolab
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:14
🔁 Restarting kernel...

In [ ]:
#Install tRNAscan-SE from Bioconda
import condacolab
condacolab.check()
!conda install -c bioconda trnascan-se -y

In [3]:
!tRNAscan-SE -h

tRNAscan-SE 2.0.12 (Nov 2022)
Copyright (C) 2022 Patricia Chan and Todd Lowe
                   University of California Santa Cruz
Freely distributed under the GNU General Public License (GPLv3)


Usage: tRNAscan-SE [-options] <FASTA file(s)>

  Scan a sequence file for tRNAs
   -- default: use Infernal & tRNA covariance models
      with eukaryotic sequences
      (use 'Search Mode Options' below to scan other types of sequences)

Search Mode Options:

  -E                          : search for eukaryotic tRNAs (default)
  -B                          : search for bacterial tRNAs
  -A                          : search for archaeal tRNAs
  -M <model>                  : search for mitochondrial tRNAs
                                  options: mammal, vert
  -O                          : search for other organellar tRNAs
  -G                          : use general tRNA model (cytoslic tRNAs from all 3 domains included)
  --mt <model>                : use mito tRNA models for cytosolic/mito detemination
                                  (if not specified, only cytosolic isotype-specific model scan will be performed)
  -I                          : search using Infernal
                                  default use with -E, -B, -A, or -G; optional for -O
      --max                   : maximum sensitivity mode - search using Infernal without hmm filter (very slow)
  -L                          : search using the legacy method (tRNAscan, EufindtRNA, and COVE)
                                  use with -E, -B, -A or -G
  -C  --cove                  : search using COVE analysis only (legacy, extremely slow)
                                  default use with -O
  -H  --breakdown             : show breakdown of primary and secondary structure components to
                                  covariance model bit scores
  -D  --nopseudo              : disable pseudogene checking

Output options:

  -o  --output <file>         : save final results in <file>
  -f  --struct <file>         : save tRNA secondary structures to <file>
  -s  --isospecific <file>    : save results using isotype-specific models in <file>
  -m  --stats <file>          : save statistics summary for run in <file>
                                  (speed, # tRNAs found in each part of search, etc)
  -b  --bed <file>            : save results in BED file format of <file>
  -j  --gff <file>            : save results in GFF3 file format of <file>
  -a  --fasta <file>          : save predicted tRNA sequences in FASTA file format of <file>
  -l  --log <file>            : save log of program progress in <file>
  --detail                    : display prediction outputs in detailed view
  --brief                     : brief output format (no column headers)

  -? #                       : '#' in place of <file> chooses default name for output files
  -p  --prefix <label>        : use <label> prefix for all default output file names

  -d  --progress              : display program progress messages
  -q  --quiet                 : quiet mode (credits & run option selections suppressed)
  -y  --hitsrc                : show origin of hits (Ts=tRNAscan 1.4, Eu=EufindtRNA,
                                  Bo=Both Ts and Eu, Inf=Infernal)

Specify Alternate Cutoffs / Data Files:

  -X  --score <score>         : set cutoff score (in bits) for reporting tRNAs (default=20)
  -g  --gencode <file>        : use alternate genetic codes specified in <file> for
                                  determining tRNA type
  -z  --pad <number>          : use <number> nucleotides padding when passing first-pass
                                  tRNA bounds predictions to CM analysis (default=8)
  --len <length>              : set max length of tRNA intron+variable region for legacy search mode
                                  (default=116bp)
Misc Options:

  -h  --help                  : print this help message
  -c  --conf <file>           : tRNAscan-SE configuration file (default: tRNAscan-SE.conf)
  -Q  --forceow               : do not prompt user before overwriting pre-existing
                                  result files  (for batch processing)

  --match <EXPR>              : search only sequences with names matching <EXPR> string
                                  (<EXPR> may contain * or ? wildcard chars)
  --search <EXPR>             : start search at sequence with name matching <EXPR> string
                                  and continue to end of input sequence file(s)
Special Advanced Options (for testing & special purposes)

  -U                          : search for tRNAs with alternate models defined in configuration file

  -t  --tscan                 : search using tRNAscan only (defaults to strict params)
  --tmode <mode>              : explicitly set tRNAscan params, where <mode>=R or S
                                  (R=relaxed, S=strict tRNAscan v1.3 params)

  -v  --verbose <file>        : save verbose tRNAscan 1.3 output to <file>
  --nomerge                   : Keep redundant tRNAscan 1.3 hits (don't filter out multiple
                                  predictions per tRNA identification)
  -e  --eufind                : search using Eukaryotic tRNA finder (EufindtRNA) only
                                  (defaults to Normal seach parameters when run alone,
                                  or to Relaxed search params when run with Cove)
  --emode <mode>              : explicitly set EufindtRNA params, where <mode>=R, N, or S
                                  (relaxed, normal, or strict)

  --iscore <score>            : manually set "intermediate" cutoff score for EufindtRNA
  -r  --fsres <file>          : save first-pass scan results from EufindtRNA, tRNAscan, or
                                  Infernal hmm in <file> in tabular results format
  --mid                       : fast scan mode - search using Infernal with mid-level strictness of hmm filter
  -F  --falsepos <file>       : save first-pass candidate tRNAs in <file> that were then
                                  found to be false positives by second-pass analysis
  --missed <file>             : save all seqs that do NOT have at least one
                                  tRNA prediction in them (aka "missed" seqs)
  --thread <number>           : number of threads used for running infernal (default is to use available threads)

In [11]:
!tRNAscan-SE --fasta tRNAscan-seq-output.fasta -f tRNAscan-struct-output.txt a_fumigatus.fna

WARNING: tRNAscan-seq-output.fasta exists already.

 (O)verwrite file, (A)ppend to file, or (Q)uit program? O

 Overwriting tRNAscan-seq-output.fasta...

WARNING: tRNAscan-struct-output.txt exists already.

 (O)verwrite file, (A)ppend to file, or (Q)uit program? O

 Overwriting tRNAscan-struct-output.txt...

tRNAscan-SE v.2.0.12 (Nov 2022) - scan sequences for transfer RNAs
Copyright (C) 2022 Patricia Chan and Todd Lowe
                   University of California Santa Cruz
Freely distributed under the GNU General Public License (GPLv3)

------------------------------------------------------------
Sequence file(s) to search:        a_fumigatus.fna
Search Mode:                       Eukaryotic
Results written to:                Standard output
Output format:                     Tabular
Searching with:                    Infernal First Pass->Infernal
Isotype-specific model scan:       Yes
Covariance model:                  /usr/local/lib/tRNAscan-SE/models/TRNAinf-euk.cm
                                   /usr/local/lib/tRNAscan-SE/models/TRNAinf-euk-SeC.cm
Infernal first pass cutoff score:  10

Temporary directory:               /tmp
tRNA secondary structure
    predictions saved to:          tRNAscan-struct-output.txt
Predicted tRNA sequences
    saved to:                      tRNAscan-seq-output.fasta
------------------------------------------------------------

Status: Phase I: Searching for tRNAs with HMM-enabled Infernal
Status: Phase II: Infernal verification of candidate tRNAs detected with first-pass scan
Sequence    		tRNA   	Bounds 	tRNA	Anti	Intron Bounds	Inf
Name        	tRNA #	Begin  	End    	Type	Codon	Begin	End	Score	Note
--------    	------	-----  	------ 	----	-----	-----	----	------	------
NC_007194.1 	1	336400 	336506 	Sup	CTA	336446	336470	33.6	pseudo
NC_007194.1 	2	766126 	766213 	Asp	GTC	766163	766178	55.7
NC_007194.1 	3	917096 	917192 	Ser	TGA	917133	917148	64.4
NC_007194.1 	4	1380646	1380717	Glu	TTC	0	0	46.8
NC_007194.1 	5	1380814	1380885	Glu	TTC	0	0	52.1
NC_007194.1 	6	1461859	1461966	Met	CAT	1461897	1461930	72.0
NC_007194.1 	7	1609608	1609688	Ser	AGA	0	0	70.7
NC_007194.1 	8	1651256	1651326	Gly	GCC	0	0	60.9
NC_007194.1 	9	2281487	2281558	Gln	CTG	0	0	64.1
NC_007194.1 	10	2282077	2282148	Gln	CTG	0	0	63.4
NC_007194.1 	11	2282224	2282295	Gln	CTG	0	0	64.1
NC_007194.1 	12	2426522	2426602	Ser	GCT	0	0	80.4
NC_007194.1 	13	2727249	2727336	Asp	GTC	2727286	2727301	55.7
NC_007194.1 	14	2907410	2907480	Gly	GCC	0	0	60.9
NC_007194.1 	15	3107447	3107536	Pro	AGG	3107483	3107500	63.7
NC_007194.1 	16	3759573	3759657	Tyr	GTA	3759611	3759621	64.3
NC_007194.1 	17	3760089	3760173	Tyr	GTA	3760127	3760137	64.3
NC_007194.1 	18	3802349	3802437	Pro	AGG	3802385	3802401	63.8
NC_007194.1 	19	3909273	3909368	Val	CAC	3909310	3909332	58.0
NC_007194.1 	20	4157779	4157850	Gly	TCC	0	0	70.0
NC_007194.1 	21	4489501	4489430	Glu	CTC	0	0	57.4
NC_007194.1 	22	4333677	4333579	Pro	CGG	4333641	4333614	50.0
NC_007194.1 	23	3761792	3761708	Tyr	GTA	3761754	3761744	64.3
NC_007194.1 	24	3761229	3761145	Tyr	GTA	3761191	3761181	64.3
NC_007194.1 	25	3760797	3760713	Tyr	GTA	3760759	3760749	64.3
NC_007194.1 	26	3698876	3698805	Pro	TGG	0	0	68.9
NC_007194.1 	27	2425996	2425916	Ser	GCT	0	0	80.4
NC_007194.1 	28	2425454	2425374	Ser	GCT	0	0	80.4
NC_007194.1 	29	2280625	2280554	Gln	CTG	0	0	64.1
NC_007194.1 	30	2279068	2278997	Gln	CTG	0	0	63.4
NC_007194.1 	31	1609041	1608961	Ser	AGA	0	0	70.7
NC_007194.1 	32	1387319	1387248	Glu	TTC	0	0	46.8
NC_007194.1 	33	767355 	767268 	Asp	GTC	767318	767303	55.7
NC_007195.1 	1	463802 	463882 	Ser	AGA	0	0	70.7
NC_007195.1 	2	935026 	935097 	Ala	AGC	0	0	71.1
NC_007195.1 	3	937478 	937549 	Ala	AGC	0	0	71.1
NC_007195.1 	4	1301238	1301318	Ser	AGA	0	0	70.7
NC_007195.1 	5	1691910	1691982	Trp	CCA	0	0	61.0
NC_007195.1 	6	2549759	2549860	Ala	TGC	2549796	2549824	63.3
NC_007195.1 	7	2619790	2619861	Glu	TTC	0	0	63.0
NC_007195.1 	8	2993163	2993234	Arg	ACG	0	0	77.9
NC_007195.1 	9	3830552	3830664	Leu	AAG	3830591	3830618	69.9
NC_007195.1 	10	4365818	4365928	Leu	CAG	4365856	4365884	59.0
NC_007195.1 	11	4499991	4500062	Thr	CGT	0	0	84.0
NC_007195.1 	12	4722232	4722338	Met	CAT	4722270	4722302	72.1
NC_007195.1 	13	4667163	4667051	Leu	AAG	4667124	4667097	69.9
NC_007195.1 	14	4182933	4182861	Lys	CTT	0	0	83.7
NC_007195.1 	15	3631928	3631830	Val	CAC	3631891	3631866	57.1
NC_007195.1 	16	2412140	2412028	Leu	AAG	2412101	2412074	69.9
NC_007195.1 	17	1691252	1691180	Trp	CCA	0	0	61.0
NC_007195.1 	18	1690720	1690648	Trp	CCA	0	0	61.0
NC_007195.1 	19	1651778	1651707	Arg	ACG	0	0	78.9
NC_007195.1 	20	1301538	1301452	Asp	GTC	1301501	1301487	55.7
NC_007195.1 	21	937016 	936945 	Ala	AGC	0	0	71.1
NC_007195.1 	22	934042 	933971 	Ala	AGC	0	0	71.1
NC_007195.1 	23	465305 	465235 	Gly	GCC	0	0	60.9
NC_007195.1 	24	143028 	142956 	Thr	AGT	0	0	86.2
NC_007195.1 	25	87180  	87109  	Arg	ACG	0	0	77.9
NC_007196.1 	1	108846 	108919 	Ile	AAT	0	0	77.2
NC_007196.1 	2	115480 	115567 	Phe	GAA	115517	115531	72.3
NC_007196.1 	3	163221 	163293 	Thr	AGT	0	0	86.2
NC_007196.1 	4	395422 	395493 	Cys	GCA	0	0	76.4
NC_007196.1 	5	531049 	531120 	Ala	AGC	0	0	71.1
NC_007196.1 	6	821186 	821257 	Arg	ACG	0	0	77.9
NC_007196.1 	7	2145343	2145455	Leu	AAG	2145382	2145409	69.9
NC_007196.1 	8	2210063	2210170	Met	CAT	2210101	2210134	72.0
NC_007196.1 	9	2342082	2342153	Arg	CCG	0	0	68.9
NC_007196.1 	10	2345014	2345085	Arg	CCG	0	0	67.1
NC_007196.1 	11	2793260	2793333	Ile	AAT	0	0	76.5
NC_007196.1 	12	2793697	2793770	Ile	AAT	0	0	76.5
NC_007196.1 	13	3556767	3556837	Gly	GCC	0	0	60.9
NC_007196.1 	14	3583456	3583528	Lys	CTT	0	0	83.7
NC_007196.1 	15	3571414	3571342	Lys	CTT	0	0	83.7
NC_007196.1 	16	3324408	3324278	Undet	NNN	0	0	26.2	pseudo
NC_007196.1 	17	2792050	2791977	Ile	AAT	0	0	76.5
NC_007196.1 	18	1149522	1149451	Arg	TCG	0	0	77.8
NC_007196.1 	19	1149267	1149195	Lys	CTT	0	0	83.7
NC_007196.1 	20	979297 	979210 	Asp	GTC	979260	979245	55.7
NC_007196.1 	21	900660 	900573 	Asp	GTC	900623	900608	55.7
NC_007196.1 	22	741446 	741375 	Ala	AGC	0	0	71.1
NC_007196.1 	23	577205 	577117 	Pro	AGG	577169	577153	63.8
NC_007196.1 	24	493923 	493852 	Arg	TCG	0	0	69.8
NC_007196.1 	25	401933 	401862 	Cys	GCA	0	0	76.1
NC_007196.1 	26	289763 	289692 	Ala	AGC	0	0	71.1
NC_007196.1 	27	179048 	178975 	Asn	GTT	0	0	78.9
NC_007197.1 	1	420996 	421076 	Ser	AGA	0	0	70.7
NC_007197.1 	2	2000974	2001046	Thr	AGT	0	0	86.2
NC_007197.1 	3	2410166	2410238	Thr	AGT	0	0	86.2
NC_007197.1 	4	3456951	3457064	Leu	CAA	3456988	3457020	59.3
NC_007197.1 	5	3470061	3470144	His	GTG	3470098	3470109	52.2
NC_007197.1 	6	3650153	3650223	Gly	GCC	0	0	60.9
NC_007197.1 	7	3456679	3456566	Leu	CAA	3456642	3456610	59.3
NC_007197.1 	8	2409096	2409026	Gly	GCC	0	0	60.9
NC_007197.1 	9	2307984	2307898	Gly	CCC	2307947	2307933	57.0
NC_007197.1 	10	1817040	1816967	Ile	AAT	0	0	77.2
NC_007197.1 	11	1213130	1213043	Thr	TGT	1213094	1213079	76.7
NC_007197.1 	12	913009 	912922 	Ile	TAT	912971	912958	65.6
NC_007197.1 	13	722485 	722398 	Pro	AGG	722449	722434	63.8
NC_007198.1 	1	883190 	883272 	Lys	TTT	883228	883236	71.2
NC_007198.1 	2	883581 	883709 	Thr	TGT	883619	883673	63.4
NC_007198.1 	3	1440395	1440499	Ala	TGC	1440432	1440463	63.2
NC_007198.1 	4	1440602	1440673	Ala	TGC	0	0	78.9
NC_007198.1 	5	1723332	1723403	Glu	CTC	0	0	54.0
NC_007198.1 	6	2114322	2114394	Val	TAC	0	0	79.2
NC_007198.1 	7	2535907	2535978	iMet	CAT	0	0	68.5
NC_007198.1 	8	2557308	2557378	His	GTG	0	0	53.9
NC_007198.1 	9	3086241	3086311	Gly	GCC	0	0	60.9
NC_007198.1 	10	3171825	3171912	Phe	GAA	3171862	3171876	76.2
NC_007198.1 	11	3171999	3172086	Phe	GAA	3172036	3172050	73.7
NC_007198.1 	12	3206972	3207043	Glu	CTC	0	0	54.0
NC_007198.1 	13	3207244	3207315	Pro	TGG	0	0	68.9
NC_007198.1 	14	3207575	3207646	Glu	CTC	0	0	54.0
NC_007198.1 	15	3372970	3373059	Asn	GTT	3373008	3373023	65.8
NC_007198.1 	16	3703632	3703727	Cys	GCA	3703668	3703691	62.2
NC_007198.1 	17	3575251	3575180	Glu	CTC	0	0	54.0
NC_007198.1 	18	3374656	3374565	Asn	GTT	3374618	3374601	66.6
NC_007198.1 	19	3374293	3374204	Asn	GTT	3374255	3374240	65.8
NC_007198.1 	20	3373659	3373563	Asn	GTT	3373621	3373599	65.5
NC_007198.1 	21	3208796	3208725	Glu	CTC	0	0	54.0
NC_007198.1 	22	3208340	3208269	Glu	CTC	0	0	54.0
NC_007198.1 	23	3169866	3169779	Phe	GAA	3169829	3169815	76.2
NC_007198.1 	24	3169547	3169460	Phe	GAA	3169510	3169496	76.2
NC_007198.1 	25	2691226	2691096	Leu	TAA	2691189	2691140	65.1
NC_007198.1 	26	2687508	2687436	Lys	CTT	0	0	83.7
NC_007198.1 	27	2654429	2654358	Ala	CGC	0	0	80.7
NC_007198.1 	28	2570024	2569912	Leu	AAG	2569985	2569958	69.9
NC_007198.1 	29	2565008	2564938	His	GTG	0	0	60.3
NC_007198.1 	30	2561769	2561698	Gly	TCC	0	0	70.0
NC_007198.1 	31	2538536	2538465	iMet	CAT	0	0	68.5
NC_007198.1 	32	2538092	2538021	iMet	CAT	0	0	68.5
NC_007198.1 	33	1903658	1903588	Gly	GCC	0	0	60.9
NC_007198.1 	34	1723131	1723060	Glu	CTC	0	0	54.0
NC_007198.1 	35	321680 	321610 	Gly	GCC	0	0	60.9
NC_007199.1 	1	126214 	126287 	Val	AAC	0	0	69.8
NC_007199.1 	2	248352 	248435 	Gln	TTG	248389	248400	59.4
NC_007199.1 	3	617113 	617210 	Thr	TGT	617150	617174	63.3
NC_007199.1 	4	874333 	874413 	Ser	GCT	0	0	80.4
NC_007199.1 	5	1574776	1574860	Thr	CGT	1574812	1574824	71.2
NC_007199.1 	6	2165147	2165219	Thr	AGT	0	0	86.2
NC_007199.1 	7	3140471	3140558	Pro	AGG	3140507	3140522	63.8
NC_007199.1 	8	3401235	3401345	Leu	CAG	3401273	3401301	56.2
NC_007199.1 	9	3477652	3477722	Gly	GCC	0	0	60.9
NC_007199.1 	10	3587601	3587672	Arg	ACG	0	0	77.9
NC_007199.1 	11	3438601	3438530	Arg	ACG	0	0	77.9
NC_007199.1 	12	3400535	3400425	Leu	CAG	3400497	3400469	58.6
NC_007199.1 	13	2164940	2164868	Thr	AGT	0	0	86.2
NC_007199.1 	14	847831 	847760 	Arg	ACG	0	0	77.9
NC_007199.1 	15	809379 	809244 	Gly	TCC	809340	809286	46.8
NC_007199.1 	16	713999 	713928 	Arg	ACG	0	0	77.9
NC_007199.1 	17	596224 	596153 	Arg	CCT	0	0	71.5
NC_007199.1 	18	490809 	490721 	Asp	GTC	490772	490756	55.6
NC_007200.1 	1	103767 	103840 	Val	AAC	0	0	69.8
NC_007200.1 	2	114031 	114102 	Arg	TCT	0	0	85.4
NC_007200.1 	3	133533 	133629 	Ser	CGA	133570	133585	64.1
NC_007200.1 	4	220338 	220409 	Gly	TCC	0	0	70.0
NC_007200.1 	5	689334 	689419 	Pro	CGG	689370	689384	49.9
NC_007200.1 	6	1156256	1156327	Ala	AGC	0	0	71.1
NC_007200.1 	7	994880 	994809 	Arg	ACG	0	0	77.9
NC_007200.1 	8	817375 	817263 	Leu	AAG	817336	817309	69.9
NC_007200.1 	9	632559 	632487 	Lys	CTT	0	0	83.7
NC_007200.1 	10	632409 	632337 	Lys	CTT	0	0	83.7
NC_007200.1 	11	631929 	631857 	Lys	CTT	0	0	83.7
NC_007200.1 	12	133143 	133017 	Ser	CGA	133106	133061	66.2
NC_007200.1 	13	87486  	87376  	Leu	CAG	87448	87420	58.6
NC_007201.1 	1	1009806	1009879	Val	AAC	0	0	69.8
NC_007201.1 	2	1010165	1010238	Val	AAC	0	0	70.5
NC_007201.1 	3	1011735	1011808	Val	AAC	0	0	68.4
NC_007201.1 	4	1016439	1016512	Val	AAC	0	0	69.8
NC_007201.1 	5	1023658	1023746	Asp	GTC	1023695	1023711	55.6
NC_007201.1 	6	1409471	1409558	Asp	GTC	1409508	1409523	55.7
NC_007201.1 	7	1422869	1422953	Ala	CGC	1422905	1422917	67.7
NC_007201.1 	8	1428297	1428368	Gln	CTG	0	0	62.9
NC_007201.1 	9	1674926	1674997	iMet	CAT	0	0	68.5
NC_007201.1 	10	1756466	1756578	Met	CAT	1756504	1756542	64.5
NC_007201.1 	11	1618840	1618770	His	GTG	0	0	60.3
NC_007201.1 	12	1434776	1434703	Ile	AAT	0	0	77.2
NC_007201.1 	13	1315335	1315262	Val	AAC	0	0	69.8
NC_007201.1 	14	1106893	1106808	Gln	TTG	1106856	1106843	63.4
NC_007201.1 	15	970558 	970485 	Ile	AAT	0	0	76.5
NC_007201.1 	16	665850 	665780 	Gly	GCC	0	0	60.9
NC_007201.1 	17	648049 	647970 	Arg	CCT	648013	648006	62.4

In [ ]:
odef commit_and_push(repo_url, message):
    import os
    import subprocess
    from google.colab import userdata

    try:
        # change your username from mine to yours.
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        !git add .
        !git commit -m {message}
        !git push https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git
        print("Changes Saved to GitHub!")
    except Exception as e:
        print(e)

# Only call this function if you want to
def catch_up_to_main_repo():
    import os
    from google.colab import userdata
    try:
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        main_repo = "https://github.com/nkmwicz/fungal-temp-analysis.git"
        !git remote add upstream {main_repo}
        !git fetch upstream
        !git merge upstream/main
        !git push https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git
    except Exception as e:
        print(e)

In [ ]:
# ----Keep as last cell----
# Use to save changes in repo that are not in this file.
# To save this file, use ctrl + s
# Then set commit message location, branch, etc.

# Change repo url to your forked url
url = "https://github.com/guth-metzlerr/fungal-temp-analysis.git"
# Change commit message
commit_and_push(url, "Added deleteme file for test")

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
To https://github.com/guth-metzlerr/fungal-temp-analysis.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/guth-metzlerr/fungal-temp-analysis.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Changes Saved to GitHub!